# Generated by Django 5.2 on 2025-06-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0001_initial"),
    ]

    operations = []
